services:
  m1:
    image: mysql:8-oracle
    container_name: m1
    restart: always
    volumes:
      - ./m1/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./m1/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "33061:3306"
    networks:
      - demo1

  m2:
    image: mysql:8-oracle
    container_name: m2
    restart: always
    volumes:
      - ./m2/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./m2/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "33062:3306"
    networks:
      - demo1

  m3:
    image: mysql:8-oracle
    container_name: m3
    restart: always
    volumes:
      - ./m3/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./m3/:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "33063:3306"
    networks:
      - demo1

networks:
  demo1:
    driver: bridge
